title: Dong Yul's Blog
description: My Personal Blog
author: Dong Yul Oh
github: https://github.com/DongYuls
about: A.I Researcher, Department of Radiology, Seoul National University Bundang Hospital.
disqus_shortname: None
google_analytics: UA-XXXXXXXX-Y
avatar_url: /static/img/my_avatar.png

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    # - icon: fa-facebook
    #   link: "#"
    # - icon: fa-twitter
    #   link: "https://twitter.com/agusmakmun6"
    # - icon: fa-linkedin
    #   link: "https://www.linkedin.com/in/summonagus"
    # - icon: fa-stack-exchange
    #   link: "#"
    - icon: fa-github
      link: "https://github.com/DongYuls"

# share:
#   twitter_username: agusmakmun6
#   fb_appid: 1749788565247320

urls:
    - text: About Me
      url: /about/
    - text: My Projects
      url: /projects/
    # - text: XML Feed
    #   url: /feed.xml

url: "https://dongyuls.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
